(() => {
'use strict';
const root=document.createElement('main');root.className='request-board';root.hidden=true;
root.innerHTML=`<p class="kicker">YESMOA / PURCHASE REQUEST</p><h1 tabindex="-1">매입 신청</h1><p>판매할 중고 물품을 등록하면 확인 후 연락드립니다.</p><p class="notice" id="board-status" role="status" aria-live="polite"></p><section class="auth"><div id="account"></div><form id="login-form"><label for="login-email">이메일 로그인</label><input id="login-email" type="email" required autocomplete="email" placeholder="로그인 링크를 받을 이메일"><button type="submit">로그인 링크 받기</button></form><button id="logout" hidden>로그아웃</button></section><section id="request-list"><div class="toolbar"><input id="request-search" aria-label="제목 검색" placeholder="제목을 검색하세요"><button id="search-button">검색</button><button class="primary" id="new-request">매입 신청하기</button></div><p>개인정보와 본문은 로그인한 신청자 본인 또는 관리자만 확인할 수 있습니다.</p><div class="table-wrap"><table><thead><tr><th>번호</th><th>제목</th><th>작성자</th><th>작성일</th><th>조회수</th></tr></thead><tbody id="request-rows"></tbody></table></div><div class="pagination"><button id="previous">이전</button><span id="page-label"></span><button id="next">다음</button></div></section><section id="request-write" hidden><h2>매입 신청서 작성</h2><form class="request-form" novalidate><div class="fields" id="request-fields"></div><div class="toolbar"><button type="button" class="back-list">목록으로</button><button type="submit" class="primary" id="request-submit">신청 등록</button></div></form></section><section id="request-detail" hidden><h2>신청 상세</h2><div id="detail-content"></div><button class="back-list">목록으로</button></section>`;
document.querySelector('.site-nav').after(root);
const originals=[...document.body.children].filter(el=>el!==root&&el.tagName!=='SCRIPT'&&!el.matches('.site-nav,dialog'));
const $=s=>root.querySelector(s);const status=text=>$('#board-status').textContent=text;
let client,user=null,page=1,total=0,search='',loading=false;
const fields=[['title','제목','text',true],['category','분류','select',true],['author','작성자','text',true],['birth_date','생년월일','date',false],['phone','연락처','tel',true],['bank_name','은행명','text',false],['account_number','계좌번호','text',false],['body','본문','textarea',true]];
for(const [name,label,type,required] of fields){const wrap=document.createElement('div');if(name==='title'||name==='body')wrap.className='wide';const lab=document.createElement('label');lab.htmlFor='request-'+name;lab.textContent=label+(required?' *':'');let input=document.createElement(type==='select'?'select':type==='textarea'?'textarea':'input');input.id=lab.htmlFor;input.name=name;input.required=required;if(input.tagName==='INPUT')input.type=type;if(type==='select')for(const value of ['', '데스크톱','노트북','서버','부품','기타']){const option=new Option(value||'분류를 선택하세요',value);input.add(option);}if(type==='textarea'){input.rows=9;input.maxLength=10000;input.placeholder='제품명, 사양, 수량, 작동 여부와 상태를 적어주세요.';}else if(type!=='select'&&type!=='date')input.maxLength=name==='title'?150:100;if(type==='date')input.max=new Date().toLocaleDateString('sv-SE');const error=document.createElement('p');error.className='error';error.id=name+'-error';input.setAttribute('aria-describedby',error.id);wrap.append(lab,input,error);$('#request-fields').append(wrap);}
$('#request-fields').insertAdjacentHTML('beforeend',`<div class="wide notice"><p>수집 항목: 작성자, 이메일(로그인), 생년월일(선택), 연락처, 은행명·계좌번호(선택), 신청 내용<br>이용 목적: 매입 상담, 신청 확인 및 정산<br>보관 기간: 처리 완료 후 90일 이내 파기. 거래 성립 시 필요한 보관 기간은 별도로 안내합니다.<br>동의를 거부하면 신청할 수 없습니다. 제목은 공개되므로 개인정보를 적지 마세요.</p><label class="consent" for="request-consent"><input type="checkbox" id="request-consent" name="consent" required aria-describedby="consent-error">개인정보 수집·이용에 동의합니다. *</label><p class="error" id="consent-error"></p></div>`);
function view(which){for(const id of ['list','write','detail'])$('#request-'+id).hidden=id!==which;root.querySelector('h1').focus();}
function route(){const open=location.hash.startsWith('#requests');root.hidden=!open;originals.forEach(el=>{el.hidden=open;});if(open){view(location.hash==='#requests/new'?'write':'list');if(location.hash!=='#requests/new')loadList();root.scrollIntoView();}}
const link=document.createElement('a');link.href='#requests';link.textContent='매입 신청';document.querySelector('.nav-menu').append(link);
$('#new-request').onclick=()=>{if(!user){status('이메일로 로그인한 후 신청할 수 있습니다.');$('#login-email').focus();return;}location.hash='requests/new';};root.querySelectorAll('.back-list').forEach(b=>b.onclick=()=>{location.hash='requests';view('list');loadList();});
function friendly(error){if(/relation|column|function|schema cache|permission|row-level/i.test(error?.message||''))return '데이터베이스 설정이 아직 완료되지 않았습니다. 사이트 관리자에게 문의해주세요.';return '요청을 처리하지 못했습니다. 연결 상태를 확인하고 다시 시도해주세요.';}
async function loadList(){if(!client)return;if(loading)return;loading=true;$('#request-rows').replaceChildren();try{const {data,error}=await client.rpc('yesmoa_list_requests',{p_search:search,p_page:page});if(error)throw error;total=Number(data?.total||0);for(const row of data?.rows||[]){const tr=document.createElement('tr');for(const val of [row.number,row.title,row.author_masked,new Date(row.created_at).toLocaleDateString('sv-SE'),row.views]){const td=document.createElement('td');td.textContent=val;tr.append(td);}const button=document.createElement('button');button.className='title-button';button.textContent=row.title;button.onclick=()=>loadDetail(row.id);tr.children[1].replaceChildren(button);$('#request-rows').append(tr);}if(!total){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.textContent='등록된 매입 신청이 없습니다.';tr.append(td);$('#request-rows').append(tr);}$('#page-label').textContent=`${page} / ${Math.max(1,Math.ceil(total/10))}`;$('#previous').disabled=page===1;$('#next').disabled=page*10>=total;}catch(error){status(friendly(error));}finally{loading=false;}}
$('#search-button').onclick=()=>{search=$('#request-search').value.trim();page=1;loadList();};$('#request-search').onkeydown=e=>{if(e.key==='Enter')$('#search-button').click();};$('#previous').onclick=()=>{page--;loadList();};$('#next').onclick=()=>{page++;loadList();};
async function loadDetail(id){if(!user){status('신청 상세는 본인 또는 관리자 로그인 후 확인할 수 있습니다.');return;}try{const {data,error}=await client.rpc('yesmoa_request_detail',{p_id:id});if(error)throw error;if(!data){status('본인 신청만 확인할 수 있습니다.');return;}const out=$('#detail-content');out.replaceChildren();const dl=document.createElement('dl');for(const [name,label]of fields){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=data[name]||'미입력';dd.className='detail';dl.append(dt,dd);}out.append(dl);view('detail');}catch(error){status(friendly(error));}}
$('#login-form').onsubmit=async e=>{e.preventDefault();if(!client)return;const b=e.target.querySelector('button');b.disabled=true;try{const url=new URL(location.href);url.hash='';const {error}=await client.auth.signInWithOtp({email:$('#login-email').value.trim(),options:{emailRedirectTo:url.href}});if(error)throw error;status('로그인 링크를 이메일로 보냈습니다. 메일의 링크를 열어주세요.');}catch(error){status(friendly(error));}finally{b.disabled=false;}};
$('#logout').onclick=async()=>{const {error}=await client.auth.signOut();if(error){status('로그아웃에 실패했습니다. 다시 시도해주세요.');return;}$('.request-form').reset();$('#detail-content').replaceChildren();view('list');status('로그아웃했습니다.');};
$('.request-form').onsubmit=async e=>{e.preventDefault();const form=e.target;let valid=true;for(const input of form.elements){if(!input.name)continue;const ok=input.checkValidity()&&(!input.required||input.type==='checkbox'||input.value.trim().length>0);input.setAttribute('aria-invalid',String(!ok));$('#'+input.name+'-error').textContent=ok?'':(input.name==='consent'?'개인정보 수집·이용에 동의해주세요.':'올바른 값을 입력해주세요.');if(!ok&&valid){input.focus();valid=false;}}if(!valid)return;if(!client||!user){status('먼저 이메일로 로그인해주세요.');return;}const b=$('#request-submit');if(b.disabled)return;b.disabled=true;const payload={};for(const [name]of fields)payload[name]=form.elements[name].value.trim()||null;payload.consent=true;try{const {error}=await client.rpc('yesmoa_submit_request',{p_data:payload});if(error)throw error;form.reset();status('매입 신청이 정상적으로 접수되었습니다.');page=1;search='';$('#request-search').value='';location.hash='requests';}catch(error){status(friendly(error)+' 입력 내용은 유지됩니다.');}finally{b.disabled=false;}};
async function init(){if(location.hash.startsWith('#requests#'))history.replaceState(null,'',location.pathname+location.search+location.hash.slice('#requests'.length));const returningFromEmail=location.hash.includes('access_token=')||location.search.includes('code=');if(!window.supabase){status('로그인 기능을 불러오지 못했습니다. 새로고침해주세요.');return;}client=window.supabase.createClient('https://rkjifgvzmetzdnawehnt.supabase.co','sb_publishable_Z_M0Q7RhYEVTTsEdaW1wnw_4qP5adyy',{auth:{persistSession:false,detectSessionInUrl:true}});function account(session){user=session?.user||null;$('#account').textContent=user?'이메일 인증 완료 · '+user.email:'개인정보 보호를 위해 이메일 로그인 후 신청해주세요.';$('#login-form').hidden=!!user;$('#logout').hidden=!user;$('#detail-content').replaceChildren();}client.auth.onAuthStateChange((_event,session)=>account(session));const {data,error}=await client.auth.getSession();if(error)status('로그인 상태를 확인하지 못했습니다.');account(data?.session);if(returningFromEmail&&user)location.hash="requests";route();}
window.addEventListener('hashchange',route);init();
})();

