(() => {
  'use strict';
  const rows=[];
  const add=(category,name,brand,series='',price=null,unit='EA',usage='')=>rows.push({category,name,brand,series,price,unit,usage});
  // Existing YESMOA prices are retained. Additional catalog items require a quote.
  [["메인보드","H110 / B150 / B250 메인보드","INTEL","",16000],["메인보드","H310 / H410 메인보드","INTEL","",13000],["메인보드","AMD B450","AMD","",5000],["SSD","SSD/M2 32G","기타","공통",1500],["SSD","SSD/M2 64G","기타","공통",2000],["SSD","SSD/M2 128G","기타","공통",6500],["SSD","SSD/M2 256G","기타","공통",15000],["SSD","SSD/M2 512G","기타","공통",30000],["SSD","SSD/M2 1T","기타","공통",55000],["SSD","SSD/M2 2T","기타","공통",115000],["그래픽카드","GTX 450/440/550/950","NVIDIA","기타",7000],["그래픽카드","GTX 650/630","NVIDIA","기타",7000],["그래픽카드","GTX 750/750 Ti","NVIDIA","기타",10000],["그래픽카드","GTX 950","NVIDIA","기타",14000],["그래픽카드","GTX 960","NVIDIA","기타",18000],["그래픽카드","GTX 1050 Ti","NVIDIA","GTX 1000",38000],["그래픽카드","GTX 1060","NVIDIA","GTX 1000",21000],["그래픽카드","GTX 1070 / 1070 Ti","NVIDIA","GTX 1000",17000],["그래픽카드","RTX 2060","NVIDIA","RTX 2000",50000],["그래픽카드","RTX 3060","NVIDIA","RTX 3000",51000],["그래픽카드","RTX 3070 Ti","NVIDIA","RTX 3000",110000]].forEach(r=>add(...r));
  ['Core Ultra 7 270K Plus','Core Ultra 5 250K Plus','Core Ultra 9 285K','Core Ultra 7 265K','Core Ultra 5 245K'].forEach(n=>add('CPU','Intel '+n,'INTEL','Core Ultra 200S'));
  for(const gen of [14,13,12,11,10,9,8,7,6])for(const tier of [9,7,5,3]){if(tier===9&&gen<9)continue;add('CPU',`Intel Core i${tier}-${gen}${tier===9?'900':tier===7?'700':tier===5?'400':'100'}`,'INTEL',gen+'세대');}
  ['9950X3D','9900X3D','9800X3D','9950X','9900X','9700X','9600X','7800X3D','7700X','7600','5900X','5800X3D','5600'].forEach(n=>add('CPU','AMD Ryzen '+n,'AMD','Ryzen '+n[0]+'000'));
  for(const usage of ['데스크탑','노트북'])for(const brand of ['삼성','SK hynix','Micron','Kingston','Corsair','기타'])for(const spec of ['DDR5','DDR4','DDR3'])for(const cap of [8,16,32])add('RAM',`${brand} ${usage} ${spec} ${cap}GB`,brand,spec,null,'EA',usage);
  for(const brand of ['삼성','SK hynix','WD','Crucial','Kingston','기타'])for(const spec of ['2.5 SATA','M.2 SATA','M.2 NVMe'])for(const cap of ['256GB','512GB','1TB','2TB','4TB'])add('SSD',`${brand} ${spec} SSD ${cap}`,brand,spec);
  for(const brand of ['Seagate','WD','Toshiba','기타'])for(const cap of [.5,1,2,3,4,6,8,10,12,14,16,20])add('HDD',`${brand} HDD ${cap===.5?'500GB':cap+'TB'} SATA`,brand,cap<=.5?'500GB 이하':cap<=4?'1TB ~ 4TB':'6TB 이상');
  for(const series of ['RTX 5000','RTX 4000','RTX 3000'])for(const model of (series==='RTX 5000'?['5090','5080','5070 Ti','5070','5060 Ti 16GB','5060 Ti 8GB','5060','5050']:series==='RTX 4000'?['4090','4080 SUPER','4080','4070 Ti SUPER','4070 SUPER','4070','4060 Ti','4060']:['3090 Ti','3090','3080 Ti','3080','3070','3060 Ti','3060']))add('그래픽카드','GeForce RTX '+model,'NVIDIA',series);
  for(const model of ['9070 XT','9070','9060 XT','7900 XTX','7900 XT','7800 XT','7700 XT','7600','6950 XT','6800 XT','6700 XT','6600','5700 XT'])add('그래픽카드','Radeon RX '+model,'AMD','RX '+model[0]+'000');
  ['Arc B580','Arc B570','Arc A770','Arc A750'].forEach(n=>add('그래픽카드','Intel '+n,'INTEL','Arc'));
  for(const spec of ['Z890','B860','H810','Z790','B760','H610','B660','B560','H510'])add('메인보드',spec+' 메인보드','INTEL');
  for(const spec of ['X870E','X870','B850','B840','X670E','B650E','B650','A620','B550','X570','B450','A520'])add('메인보드',spec+' 메인보드','AMD');
  for(const brand of ['시소닉','Corsair','FSP','마이크로닉스','기타'])for(const watts of [500,600,700,750,850,1000])add('파워',`${brand} 정격 ${watts}W 파워`,brand);
  for(const brand of ['삼성/LG','Dell','ASUS','BenQ','기타 제조사'])for(const size of [20,22,23,24,27,32,39])add('모니터',`${brand} ${size}인치 LED 모니터`,brand,size+'인치');
  ['MacBook Air','MacBook Pro','iMac','Mac mini','Mac Studio','Mac Pro'].forEach(n=>add('애플',n+' · 모델 및 사양 확인','Apple'));
  ['Dell PowerEdge','HPE ProLiant','Lenovo ThinkSystem','Supermicro','Intel Xeon','AMD EPYC','서버 ECC RAM'].forEach(n=>add('서버',n,'기업 장비'));
  rows.forEach((r,id)=>r.id=id);
  const selected=new Map(),quantities=new Map();
  const categories=['전체','CPU','RAM','SSD','HDD','그래픽카드','메인보드','파워','모니터','애플','서버'];
  const dialog=document.createElement('dialog');dialog.className='catalog-dialog';dialog.setAttribute('aria-labelledby','catalog-title');
  dialog.innerHTML=`<div class="catalog-shell"><header class="catalog-head"><div><p class="catalog-kicker">YESMOA / BUYBACK</p><h2 id="catalog-title">매입 단가표</h2><p>부품의 다음 가치, 쉽고 빠르게 확인하세요.</p></div><button type="button" class="catalog-close" aria-label="단가표 닫기">×</button></header><button type="button" class="estimate-open">예상 자동 견적 <span>0</span> ↗</button><section class="estimate-panel" hidden aria-label="선택 제품 예상 견적"></section><div class="catalog-status">기존 YESMOA 등록 단가 기준 · 미등록 제품은 상담 견적</div><div class="catalog-tabs" aria-label="품목 선택"></div><div class="catalog-filters"></div><div class="catalog-search"><label for="catalog-query">모델 검색</label><input id="catalog-query" type="search" placeholder="예: RTX 5070, DDR5 32GB, 삼성"><button type="button" data-catalog-reset>초기화</button></div><div class="catalog-summary"><span role="status" aria-live="polite"></span><label>정렬 <select aria-label="단가표 정렬"><option value="default">기본 순서</option><option value="name">제품명순</option><option value="high">높은 가격순</option><option value="low">낮은 가격순</option></select></label></div><div class="catalog-table-wrap"><table><thead><tr><th scope="col">제품 / 모델</th><th scope="col">매입 단가</th><th scope="col">수량</th><th scope="col">선택</th></tr></thead><tbody></tbody></table></div><button type="button" class="catalog-more">더 보기</button><footer class="catalog-note"><strong>매입 단가 안내</strong><p>등록된 금액은 기존 YESMOA 단가표 기준입니다. 제품 상태와 검수 결과에 따라 최종 금액이 달라질 수 있습니다. 가격이 미등록된 제품은 모델·수량·상태 확인 후 견적을 안내합니다.</p><a href="tel:01095504687">매입 상담 010-9550-4687 ↗</a></footer></div>`;
  document.body.append(dialog);const fixedTop=document.createElement('div');fixedTop.className='catalog-fixed-top';const shell=dialog.querySelector('.catalog-shell');shell.prepend(fixedTop);for(const selector of ['.catalog-head','.estimate-open','.catalog-status','.catalog-tabs'])fixedTop.append(dialog.querySelector(selector));
  let category='전체', filters={}, limit=40, opener;
  const query=dialog.querySelector('input'), tbody=dialog.querySelector('tbody'), tabs=dialog.querySelector('.catalog-tabs'), filterbox=dialog.querySelector('.catalog-filters'), sort=dialog.querySelector('select');
  const button=(label,active,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('aria-pressed',String(active));b.onclick=fn;return b;};
  function drawFilters(){filterbox.replaceChildren();const subset=rows.filter(r=>r.category===category);for(const [key,label] of [['brand','제조사'],['usage','용도'],['series',category==='CPU'?'세대 / 시리즈':category==='HDD'?'용량':'규격 / 시리즈']]){const values=[...new Set(subset.map(r=>r[key]).filter(Boolean))];if(values.length<2)continue;const line=document.createElement('div'),title=document.createElement('strong');title.textContent=label;line.append(title);for(const v of ['전체',...values])line.append(button(v,(filters[key]||'전체')===v,()=>{filters[key]=v;limit=40;drawFilters();render();}));filterbox.append(line);}}
  function render(){tabs.replaceChildren(...categories.map(c=>button(c,c===category,()=>{category=c;filters={};limit=40;drawFilters();render();})));const terms=query.value.toLowerCase().trim().split(/\s+/).filter(Boolean);let results=rows.filter(r=>(category==='전체'||r.category===category)&&Object.entries(filters).every(([k,v])=>v==='전체'||r[k]===v)&&terms.every(t=>(r.name+' '+r.category+' '+r.brand+' '+r.series).toLowerCase().includes(t)));if(sort.value==='name')results.sort((a,b)=>a.name.localeCompare(b.name,'ko'));else if(sort.value!=='default')results.sort((a,b)=>a.price===null?b.price===null?0:1:b.price===null?-1:sort.value==='high'?b.price-a.price:a.price-b.price);tbody.replaceChildren();for(const r of results.slice(0,limit)){const tr=document.createElement('tr'),name=document.createElement('td'),price=document.createElement('td'),title=document.createElement('strong'),meta=document.createElement('small');title.textContent=r.name;meta.textContent=[r.category,r.brand,r.series].filter(Boolean).join(' · ');name.append(title,meta);price.textContent=r.price===null?'상담 후 견적':r.price.toLocaleString('ko-KR')+'원 / '+r.unit;price.className=r.price===null?'quote':'amount';const choice=document.createElement('td'),check=document.createElement('input');check.type='checkbox';check.checked=selected.has(r.id);check.setAttribute('aria-label',r.name+' 견적에 추가');check.onchange=()=>{if(check.checked)selected.set(r.id,quantities.get(r.id)||1);else selected.delete(r.id);drawEstimate();};const quantityCell=document.createElement('td'),quantity=document.createElement('input');quantity.type='number';quantity.min='1';quantity.max='9999';quantity.step='1';quantity.value=quantities.get(r.id)||1;quantity.className='catalog-row-quantity';quantity.setAttribute('aria-label',r.name+' 수량');quantity.oninput=()=>{const n=Math.min(9999,Math.max(1,Math.floor(Number(quantity.value)||1)));quantities.set(r.id,n);if(selected.has(r.id)){selected.set(r.id,n);drawEstimate();}};quantity.onchange=()=>quantity.value=quantities.get(r.id)||1;quantityCell.append(quantity);choice.append(check);tr.append(name,price,quantityCell,choice);tbody.append(tr);}if(!results.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=4;td.className='catalog-empty';td.textContent='검색 결과가 없습니다. 검색어 또는 필터를 변경해주세요.';tr.append(td);tbody.append(tr);}dialog.querySelector('[role=status]').textContent=`${category} · ${results.length.toLocaleString()}개 제품`;dialog.querySelector('.catalog-more').hidden=results.length<=limit;}
  const panel=dialog.querySelector('.estimate-panel');
  const money=n=>n.toLocaleString('ko-KR')+'원';
  function drawEstimate(){
    dialog.querySelector('.estimate-open span').textContent=selected.size;
    panel.replaceChildren();
    const heading=document.createElement('h3');heading.textContent='나의 예상 견적';panel.append(heading);
    let total=0,unknown=0;
    for(const [id,qty] of selected){
      const r=rows[id],line=document.createElement('div');line.className='estimate-item';
      const label=document.createElement('span');label.textContent=r.name;
      const count=document.createElement('input');count.type='number';count.min=1;count.max=9999;count.step=1;count.value=qty;count.setAttribute('aria-label',r.name+' 수량');
      count.oninput=()=>{const quantity=Math.min(9999,Math.max(1,Math.floor(Number(count.value)||1)));selected.set(id,quantity);quantities.set(id,quantity);const rowInput=tbody.querySelectorAll('input[type=number]');for(const el of rowInput){if(el.getAttribute('aria-label')===r.name+' 수량')el.value=quantity;}sum.textContent=r.price===null?'상담 필요':money(r.price*quantity);let amount=0;for(const [key,n] of selected){if(rows[key].price!==null)amount+=rows[key].price*n;}panel.querySelector('.estimate-total').textContent='등록 단가 예상 합계 '+money(amount);};count.onchange=()=>drawEstimate();
      const sum=document.createElement('strong');sum.textContent=r.price===null?'상담 필요':money(r.price*qty);
      if(r.price===null)unknown+=qty;else total+=r.price*qty;
      const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',r.name+' 선택 취소');remove.onclick=()=>{selected.delete(id);render();drawEstimate();};
      line.append(label,count,sum,remove);panel.append(line);
    }
    const result=document.createElement('p');result.className='estimate-total';result.textContent=selected.size?'등록 단가 예상 합계 '+money(total):'제품 옆 체크박스를 눌러 견적을 시작하세요.';panel.append(result);
    const note=document.createElement('p');note.className='estimate-help';note.textContent=(unknown?'가격 미등록 '+unknown+'개는 합계에서 제외되며 상담이 필요합니다. ':'')+'예상 금액이며 제품 상태와 검수 결과에 따라 최종 매입가가 달라집니다. 품목을 바꾸거나 검색해도 선택은 유지됩니다.';panel.append(note);
    if(selected.size){const clear=document.createElement('button');clear.type='button';clear.className='estimate-clear';clear.textContent='선택 모두 비우기';clear.onclick=()=>{selected.clear();render();drawEstimate();};panel.append(clear);}
  }
  dialog.querySelector('.estimate-open').onclick=()=>{panel.hidden=!panel.hidden;drawEstimate();if(!panel.hidden)panel.scrollIntoView({behavior:'smooth',block:'start'});};
  query.oninput=()=>{limit=40;render();};sort.onchange=()=>{limit=40;render();};dialog.querySelector('[data-catalog-reset]').onclick=()=>{filters={};query.value='';sort.value='default';limit=40;drawFilters();render();};dialog.querySelector('.catalog-more').onclick=()=>{limit+=40;render();};dialog.querySelector('.catalog-close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close();}});dialog.onclose=()=>{document.body.classList.remove('catalog-open');opener?.focus();};
  document.querySelectorAll('[data-open-price-modal]').forEach(el=>{if(/불량/.test(el.textContent+' '+el.getAttribute('aria-label'))||el.closest('article')?.textContent.includes('불량'))return;el.removeAttribute('data-open-price-modal');el.setAttribute('data-open-catalog','');});
  document.addEventListener('click',e=>{const trigger=e.target.closest('[data-open-catalog]');if(!trigger)return;e.preventDefault();opener=trigger;render();dialog.showModal();document.body.classList.add('catalog-open');});document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('article[data-open-catalog]')){e.preventDefault();e.target.click();}});
})();

