(() => {
'use strict';
const data=window.YESMOA_DEFECT_DATA;if(!data)return;
const dialog=document.createElement('dialog');dialog.className='defect-dialog';dialog.setAttribute('aria-labelledby','defect-title');
dialog.innerHTML=`<div class="defect-shell"><button type="button" class="defect-close" aria-label="불량 단가표 닫기">×</button><header class="defect-heading"><div class="defect-brand"><img src="assets/yesmoa-logo-mark.png" alt=""><strong></strong></div><a class="defect-website" target="_blank" rel="noopener"></a><p class="defect-eyebrow">DEFECTIVE PARTS · RESOURCE RECOVERY</p><h2 id="defect-title"></h2><p class="defect-subtitle"></p><span class="defect-date"></span></header><div class="defect-contact"><div><small>불량 부품 · 스크랩 매입 상담</small><a></a></div><p></p></div><div class="defect-controls"><label>품목 검색<input type="search" placeholder="품목명이나 브랜드를 입력하세요"></label><label>품목 구분<select><option value="전체">전체 품목</option></select></label><button type="button" class="defect-print">인쇄 / PDF 저장</button></div><p class="defect-count" role="status" aria-live="polite"></p><div class="defect-groups"></div><div class="defect-notice"><strong>매입 가격 안내</strong><p>표시 금액은 기존 등록 단가입니다. 제품 종류·상태·수량과 검수 결과에 따라 최종 매입가가 달라질 수 있습니다.</p><p>단위 안내: EA는 개당, KG는 무게 1kg당 가격입니다.</p></div></div>`;
document.body.append(dialog);dialog.querySelector('.defect-brand strong').textContent=data.brand;const website=dialog.querySelector('.defect-website');website.textContent=data.website||'https://niccol23.github.io/YESMOA/';try{const url=new URL(website.textContent);website.href=['https:','http:'].includes(url.protocol)?url.href:'https://niccol23.github.io/YESMOA/';}catch{website.href='https://niccol23.github.io/YESMOA/';}dialog.querySelector('h2').textContent=data.title;dialog.querySelector('.defect-subtitle').textContent=data.subtitle;dialog.querySelector('.defect-date').textContent='단가 기준일 '+data.date.replaceAll('-','. ');const phone=dialog.querySelector('.defect-contact a');phone.textContent=data.phone;phone.href='tel:'+data.phone.replace(/[^0-9+]/g,'');dialog.querySelector('.defect-contact p').textContent=data.address;
const input=dialog.querySelector('input'),select=dialog.querySelector('select'),groups=dialog.querySelector('.defect-groups');for(const cat of [...new Set(data.items.map(r=>r.category))]){const opt=document.createElement('option');opt.value=cat;opt.textContent=cat;select.append(opt);}
function render(){groups.replaceChildren();const terms=input.value.trim().toLowerCase().split(/\s+/).filter(Boolean);const filtered=data.items.filter(r=>(select.value==='전체'||r.category===select.value)&&terms.every(t=>(r.name+' '+r.category).toLowerCase().includes(t)));dialog.querySelector('.defect-count').textContent=`${filtered.length}개 품목 · 단가 기준일 ${data.date}`;const layout=data.layout||{left:['컴퓨터 스크랩','메인보드','노트북','모니터','알루미늄'],right:['CPU / RAM','그래픽카드','구리 / 비철','SSD / M.2']};const columns=[document.createElement('div'),document.createElement('div')];columns.forEach(c=>{c.className='defect-column';groups.append(c);});const cats=[...new Set(filtered.map(r=>r.category))];const ordered=[...layout.left,...layout.right,...cats.filter(c=>![...layout.left,...layout.right].includes(c))];for(const cat of ordered.filter(c=>cats.includes(c))){const section=document.createElement('section');section.className='defect-group';const title=document.createElement('h3');title.textContent=cat;const table=document.createElement('table');table.innerHTML='<thead><tr><th scope="col">품목</th><th scope="col">단위</th><th scope="col">시세가</th></tr></thead>';const body=document.createElement('tbody');for(const r of filtered.filter(x=>x.category===cat)){const tr=document.createElement('tr');for(const value of [r.name,r.unit,r.price===null?'—':r.price.toLocaleString('ko-KR')+'원']){const td=document.createElement('td');td.textContent=value;tr.append(td);}body.append(tr);}table.append(body);section.append(title,table);columns[layout.left.includes(cat)?0:1].append(section);}for(const col of columns){const blank=document.createElement('div');blank.className='defect-balance';blank.setAttribute('aria-hidden','true');col.append(blank);}if(!filtered.length){const p=document.createElement('p');p.textContent='검색 결과가 없습니다. 검색어를 변경해주세요.';groups.append(p);}}
let opener;input.oninput=render;select.onchange=render;dialog.querySelector('.defect-close').onclick=()=>dialog.close();dialog.onclose=()=>{document.body.classList.remove('defect-open');opener?.focus();};dialog.querySelector('.defect-print').onclick=()=>window.print();document.addEventListener('click',e=>{const target=e.target.closest('[data-open-price-modal]');if(!target)return;e.preventDefault();opener=target;render();dialog.showModal();document.body.classList.add('defect-open');});document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('article[data-open-price-modal]')){e.preventDefault();e.target.click();}});dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close();}});
})();

