'use strict';
const file=document.getElementById('file'),status=document.getElementById('status');let current=null;
function validate(r){if(!r||r.schema!=='yesmoa-spec-v1'||r.brand!=='YESMOA-COM'||typeof r.createdAt!=='string'||r.createdAt.length>80||!Array.isArray(r.items)||r.items.length<1||r.items.length>100)throw Error('YESMOA 진단 프로그램에서 저장한 결과 파일을 선택하세요.');for(const x of r.items){if(!x||typeof x.category!=='string'||typeof x.value!=='string'||x.category.length>80||x.value.length>2000)throw Error('결과 파일 형식이 올바르지 않습니다.');}return r;}
function reportText(){return 'YESMOA-COM / 내 PC 사양\n조회: '+current.createdAt+'\n\n'+current.items.map(x=>x.category+'\n'+x.value).join('\n\n')+'\n\n문의 010-9550-4687';}
function clear(){current=null;document.getElementById('report').hidden=true;document.getElementById('empty').hidden=false;document.getElementById('rows').replaceChildren();file.value='';document.getElementById('sms').removeAttribute('href');}
file.onchange=async()=>{const f=file.files[0];if(!f)return;clear();try{if(f.size>256000)throw Error('파일이 너무 큽니다. 256KB 이하의 결과 파일을 선택하세요.');const r=validate(JSON.parse(await f.text()));current=r;document.getElementById('date').textContent='조회 일시: '+r.createdAt;const rows=document.getElementById('rows');for(const x of r.items){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=x.category;dd.textContent=x.value;rows.append(dt,dd);}document.getElementById('report').hidden=false;document.getElementById('empty').hidden=true;document.getElementById('sms').href='sms:01095504687?body='+encodeURIComponent('[매입 견적 문의]\n'+reportText());status.textContent='결과를 표시했습니다. 파일 내용은 서버로 전송되지 않았습니다.';}catch(e){clear();status.textContent=e instanceof SyntaxError?'JSON 파일을 읽을 수 없습니다. 저장한 결과 파일을 다시 선택하세요.':e.message;}};
document.getElementById('clear').onclick=()=>{clear();status.textContent='결과를 지웠습니다.';};
document.getElementById('copy').onclick=async()=>{if(!current)return;try{await navigator.clipboard.writeText(reportText());status.textContent='사양을 복사했습니다.';}catch{const t=document.createElement('textarea');t.value=reportText();document.getElementById('report').append(t);t.select();status.textContent='텍스트를 선택했습니다. Ctrl+C 또는 길게 눌러 복사하세요.';}};
document.getElementById('image').onclick=()=>{if(!current)return;const c=document.createElement('canvas'),g=c.getContext('2d');c.width=900;g.font='20px sans-serif';const lines=[];for(const raw of reportText().split('\n')){let line='';for(const ch of raw){if(g.measureText(line+ch).width>800){lines.push(line);line=ch;}else line+=ch;}lines.push(line);}c.height=100+lines.length*32;g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.fillStyle='#0e735e';g.fillRect(0,0,c.width,12);g.font='20px sans-serif';g.fillStyle='#101827';lines.forEach((s,i)=>g.fillText(s,40,55+i*32));c.toBlob(b=>{if(!b){status.textContent='이미지를 만들지 못했습니다.';return;}const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='YESMOA-PC-사양.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);},'image/png');};
